---

- name: Download Scala
  get_url:
    url="http://downloads.lightbend.com/scala/{{scala_version}}/scala-{{scala_version}}.tgz"
    dest="/root/"
  register: new_scala_archive

- name: Unarchive Scala
  unarchive:
    src="/root/scala-{{scala_version}}.tgz"
    dest="/opt/"
    copy=no
  when: new_scala_archive|changed

- name: Link Scala
  file: path=/opt/scala state=link src=/opt/scala-{{scala_version}}

- name: Link Scala binary
  file: path=/home/{{user}}/bin/scala state=link src=/opt/scala/bin/scala owner={{user}} group={{user}}

- name: Install SBT apt key
  apt_key: id=642AC823 keyserver='keyserver.ubuntu.com' state=present
  register: sbtkey
  until: sbtkey|success
  retries: 5
  delay: 10

- name: Install SBT repo
  apt_repository: repo='deb https://dl.bintray.com/sbt/debian /' state=present

- name: Install SBT package
  apt: pkg=sbt state=latest

- name: Create SBT plugins directory
  file: path=/home/{{user}}/.sbt/{{sbt_version}}/plugins state=directory owner={{user}} group={{user}}

- name: Copy SBT plugins file
  template: src=plugins.sbt.j2 dest=/home/{{user}}/.sbt/{{sbt_version}}/plugins/plugins.sbt owner={{user}} group={{user}}

- name: Initialize SBT
  command: echo exit | sbt -v
  args:
    chdir: /tmp

- name: Download Eclipse for Scala
  get_url:
    url="http://downloads.typesafe.com/scalaide-pack/4.4.1-vfinal-luna-211-20160504/scala-SDK-4.4.1-vfinal-2.11-linux.gtk.x86_64.tar.gz"
    dest="/root/"
  register: new_eclipse_archive

- name: Unarchive Eclipse
  unarchive:
    src="/root/scala-SDK-4.4.1-vfinal-2.11-linux.gtk.x86_64.tar.gz"
    dest="/home/{{user}}/applications"
    copy=no owner={{user}} group={{user}}
  when: new_eclipse_archive|changed

- name: Rename Eclipse folder
  command: mv /home/{{user}}/applications/eclipse /home/{{user}}/applications/eclipse-scala
  when: new_eclipse_archive|changed

