---

- name: Install Python packages
  apt: name={{item}} state=installed
  with_items:
       - python-pip 
       - python3-pip 
       - python3-numpy
       - python3-scipy
       - python3-pandas
       # needed for matplotlib
       - libfreetype6-dev
       - pkg-config 
       - python-dev 
       - g++ 
       # needed for jupyter
       - build-essential 
       - python3-dev 

- name: Install virtualenv
  pip: name=virtualenv

- name: Create Python 3 venv
  become: yes
  become_user: "{{ user }}"
  pip:
    requirements=/vagrant/files/pip-requirements.txt
    virtualenv=/home/{{user}}/venv-3
    virtualenv_python=python3
    virtualenv_site_packages=yes

- name: Create Python 2.7 venv
  become: yes
  become_user: "{{ user }}"
  pip:
    requirements=/vagrant/files/pip-requirements.txt
    virtualenv=/home/{{user}}/venv-2.7
    virtualenv_python=python2.7
    virtualenv_site_packages=yes

