---

flink_version: 1.0.3
flink_name: flink-{{ flink_version }}-bin-hadoop26-scala_2.11
flink_mirror: http://mirror.vorboss.net
flink_checksum_uri: http://www-eu.apache.org/dist/flink/flink-{{ flink_version }}/{{ flink_name }}.tgz.sha

