---

- name: Install Maven
  apt: name=maven state=installed

- name: Download Eclipse
  get_url:
    url="{{ eclipse_mirror }}/{{ eclipse_name }}.tar.gz"
    checksum=sha512:{{ eclipse_checksum }}
    dest="/root/{{ eclipse_name }}.tar.gz"
  register: new_eclipse_archive

- name: Unarchive Eclipse
  unarchive:
    src="/root/{{ eclipse_name }}.tar.gz"
    dest="/home/{{user}}/applications"
    copy=no owner={{user}} group={{user}}
  when: new_eclipse_archive|changed

- name: Rename Eclipse folder
  command: mv /home/{{user}}/applications/eclipse /home/{{user}}/applications/eclipse-jee
  args:
    creates: /home/{{user}}/applications/eclipse-jee

